# Generated by Django 3.0.5 on 2020-04-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('opw_id', models.IntegerField(default=0)),
                ('country', models.CharField(default='', max_length=80)),
                ('state', models.CharField(default='', max_length=80)),
                ('coord_lon', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('coord_lat', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
            ],
        ),
    ]
