# Generated by Django 3.0.5 on 2020-05-01 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0003_popularity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecast',
            options={'ordering': ['-loadingtime']},
        ),
        migrations.AlterModelOptions(
            name='popularity',
            options={'ordering': ['-pickeddate']},
        ),
        migrations.RenameField(
            model_name='popularity',
            old_name='cityid',
            new_name='city',
        ),
    ]
