# Generated by Django 3.0.5 on 2020-05-01 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0004_auto_20200501_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecast',
            old_name='cityid',
            new_name='city',
        ),
    ]
